#%RAML 1.0 NamedExample
  {
    "item": "mic",
    "category": "electronic",
    "quantity": 10,
    "price": 24.5,
    "manufacturedDate": 2020-02-02,
    "expiryDate": 2040-02-02,
    "suppilerName": "ABC Suppliers",
    "madeInCountry": "India"
  }