#%RAML 1.0 NamedExample
{
  "order" : {    
    "orderId": "ord45",
    "item": "mic",
    "quantity" : 8,
    "orderDate": 2021-11-10,
    "customerRef": "009393",
    "status": "new"
    },
  "customer": {
    "name": "Vamshi",
    "contactNo": "933-565-3434",
    "street": "James street",
    "city" : "Chicago"
  }
}